/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.booking.system;

import static hotel.booking.system.StaffManageRoom.jTableManageRoom;
import static hotel.booking.system.manageBooking.jTableManageBooking;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author qi xian
 */
public class manageStaff extends javax.swing.JFrame {

    /**
     * Creates new form manageStaff
     */
    public manageStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAddRoom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManageStaff = new javax.swing.JTable();
        btnUpdateStaff = new javax.swing.JButton();
        btnDeleteStaff = new javax.swing.JButton();
        txtSearchStaff = new javax.swing.JTextField();
        btnSearchStaff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblAddRoom.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblAddRoom.setForeground(new java.awt.Color(0, 182, 204));
        lblAddRoom.setText("Manage Staff");
        lblAddRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 181, 204));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jTableManageStaff.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTableManageStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff Id", "Staff Name", "Username", "Password", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableManageStaff);

        btnUpdateStaff.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateStaff.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnUpdateStaff.setForeground(new java.awt.Color(0, 182, 204));
        btnUpdateStaff.setText("Update");
        btnUpdateStaff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnUpdateStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUpdateStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateStaffMouseExited(evt);
            }
        });
        btnUpdateStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStaffActionPerformed(evt);
            }
        });

        btnDeleteStaff.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteStaff.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnDeleteStaff.setForeground(new java.awt.Color(0, 182, 204));
        btnDeleteStaff.setText("Delete");
        btnDeleteStaff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnDeleteStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeleteStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteStaffMouseExited(evt);
            }
        });
        btnDeleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStaffActionPerformed(evt);
            }
        });

        txtSearchStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchStaffActionPerformed(evt);
            }
        });

        btnSearchStaff.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchStaff.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnSearchStaff.setForeground(new java.awt.Color(0, 182, 204));
        btnSearchStaff.setText("Search");
        btnSearchStaff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnSearchStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSearchStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchStaffMouseExited(evt);
            }
        });
        btnSearchStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAddRoom)
                        .addGap(175, 175, 175)
                        .addComponent(txtSearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnUpdateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(371, 371, 371)
                        .addComponent(btnDeleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(485, 485, 485))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchStaff, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAddRoom)
                        .addComponent(jLabel1)
                        .addComponent(txtSearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnDeleteStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 140, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnUpdateStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateStaffMouseEntered
        btnUpdateStaff.setBackground(Color.cyan);
        btnUpdateStaff.setForeground(Color.white);
    }//GEN-LAST:event_btnUpdateStaffMouseEntered

    private void btnUpdateStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateStaffMouseExited
        btnUpdateStaff.setBackground(new Color(255,255,255));
        btnUpdateStaff.setForeground(new Color(0,182,204));
    }//GEN-LAST:event_btnUpdateStaffMouseExited

    private void btnUpdateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStaffActionPerformed

        DefaultTableModel model = (DefaultTableModel)jTableManageStaff.getModel();
        int selectedRowIndex = jTableManageStaff.getSelectedRow();

        if(selectedRowIndex >= 0) {
            
        //passing value form staffManageroom.java to all textbox and combob
        updateStaff transfer = new updateStaff();
        updateStaff.txtStaffId.setText(model.getValueAt(selectedRowIndex, 0).toString());
        updateStaff.txtStaffName.setText(model.getValueAt(selectedRowIndex, 1).toString());
        updateStaff.txtStaffUsername1.setText(model.getValueAt(selectedRowIndex, 2).toString());
        updateStaff.txtStaffPassword.setText(model.getValueAt(selectedRowIndex, 3).toString());
        
          
        updateStaff.txtStaffEmail.setText(model.getValueAt(selectedRowIndex, 4).toString());
        

        transfer.setVisible(true);}else{
            JOptionPane.showMessageDialog(null, "Please select a row!");
        
        }
    }//GEN-LAST:event_btnUpdateStaffActionPerformed

    private void btnDeleteStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteStaffMouseEntered
        btnDeleteStaff.setBackground(Color.cyan);
        btnDeleteStaff.setForeground(Color.white);
    }//GEN-LAST:event_btnDeleteStaffMouseEntered

    private void btnDeleteStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteStaffMouseExited
        btnDeleteStaff.setBackground(new Color(255,255,255));
        btnDeleteStaff.setForeground(new Color(0,182,204));
    }//GEN-LAST:event_btnDeleteStaffMouseExited

    private void btnDeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStaffActionPerformed

        DefaultTableModel model = (DefaultTableModel)jTableManageStaff.getModel();
        int selectedRowIndex = jTableManageStaff.getSelectedRow();
        
        
        
        if(selectedRowIndex >=0){

        String staffIDToDeleteFrom = (model.getValueAt(selectedRowIndex, 0).toString());
        int staffIDToDeleteFromint = Integer.parseInt(staffIDToDeleteFrom);

        staff obj = new staff();

        obj.DeleteStaff(staffIDToDeleteFromint);
        
        
        
         //refresh jtable
      String filePath = "C:\\Users\\qi xian\\Documents\\NetBeansProjects\\HOTEL BOOKING SYSTEM\\staff.txt";
        File file = new File(filePath);
        jTableManageStaff.setRowHeight(30);
         jTableManageStaff.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 16));
        
        
        try{
            BufferedReader br = new BufferedReader(new FileReader(file));
            
             model.setRowCount(0);
            Object[] tableLines = br.lines().toArray();
            
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                int index1 = line.indexOf(',');
                
                
                
                
                String[] dataRow = line.split(",");
                
                    String[] tablerow ;
                    tablerow = new String[10];
                
                
                String email = dataRow[3];
                 tablerow[4] = email;
                
                
                String Password = dataRow[1];
                tablerow[3] = Password;
                
                
                 String Username = dataRow[0];
                  tablerow[2] = Username;
                
                
                 
                
                String staffId = dataRow[5];
                int staffIdLength = staffId.length();
                String staffIdComplete = staffId.substring(11,staffIdLength);
                tablerow[0] = staffIdComplete;
                
                
                String staffNamezz = dataRow[2];
                 tablerow[1] = staffNamezz;
                
               
                model.addRow(tablerow);
            }
            
            
            
        } catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row!");
        
        }
    }//GEN-LAST:event_btnDeleteStaffActionPerformed

    private void txtSearchStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchStaffActionPerformed

    private void btnSearchStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchStaffMouseEntered
        btnSearchStaff.setBackground(Color.cyan);
        btnSearchStaff.setForeground(Color.white);
    }//GEN-LAST:event_btnSearchStaffMouseEntered

    private void btnSearchStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchStaffMouseExited
        btnSearchStaff.setBackground(new Color(255,255,255));
        btnSearchStaff.setForeground(new Color(0,182,204));
    }//GEN-LAST:event_btnSearchStaffMouseExited

    private void btnSearchStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStaffActionPerformed
        staff obj = new staff();
        obj.SerchStaff();
    }//GEN-LAST:event_btnSearchStaffActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         //refresh jtable
         
        DefaultTableModel model = (DefaultTableModel)jTableManageStaff.getModel();
        model.setRowCount(0);
        String filePath = "C:\\Users\\qi xian\\Documents\\NetBeansProjects\\HOTEL BOOKING SYSTEM\\staff.txt";
        File file = new File(filePath);
       jTableManageStaff.setRowHeight(30);
        jTableManageStaff.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 16));
        
        
        
        try{
            BufferedReader br = new BufferedReader(new FileReader(file));
            
            Object[] tableLines = br.lines().toArray();
            
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                int index1 = line.indexOf(',');
                
                
                
                
                String[] dataRow = line.split(",");
                
                    String[] tablerow ;
                    tablerow = new String[5];
                    
                    String staffId = dataRow[5];
                int staffIdLength = staffId.length();
                String staffIdComplete = staffId.substring(11,staffIdLength);
                tablerow[0] = staffIdComplete;
                
                String staffName = dataRow[2];
                 tablerow[1] = staffName;
                
                String Username = dataRow[0];
                  tablerow[2] = Username;
                
                
                String Password = dataRow[1];
                tablerow[3] = Password;
                
                
                 
                
                String emailzz = dataRow[3];
                 tablerow[4] = emailzz;
                 
                
                
                
                
                
                
               
                model.addRow(tablerow);
            }
            
            
            
        } catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteStaff;
    private javax.swing.JButton btnSearchStaff;
    private javax.swing.JButton btnUpdateStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableManageStaff;
    private javax.swing.JLabel lblAddRoom;
    public static javax.swing.JTextField txtSearchStaff;
    // End of variables declaration//GEN-END:variables
}
