/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.booking.system;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author qi xian
 */
public class newAdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form newAdminDashboard
     */
    public newAdminDashboard() {
        initComponents();
        scaleImage();
    }
    
    
     public void scaleImage(){
    //icon for make booking button
    ImageIcon icon = new ImageIcon("C:\\Users\\qi xian\\Downloads\\calendar.png");
    Image img1 = icon.getImage();
    Image imgscale1 = img1.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(imgscale1);
    lblMakeBookingPic.setIcon(scaledIcon);
    
    //icon for manage booking button
    ImageIcon icon2 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\data.png");
    Image img2 = icon2.getImage();
    Image imgscale2 = img2.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon2 = new ImageIcon(imgscale2);
    lblManageBookingPic.setIcon(scaledIcon2);
    
    
    //icon for add room button
    ImageIcon icon3 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\room.png");
    Image img3 = icon3.getImage();
    Image imgscale3 = img3.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon3 = new ImageIcon(imgscale3);
    lblAddRoompic.setIcon(scaledIcon3);
    
    //icon for manage room button
    ImageIcon icon4 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\medical-record.png");
    Image img4 = icon4.getImage();
    Image imgscale4 = img4.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon4 = new ImageIcon(imgscale4);
    lblManageRoomPic.setIcon(scaledIcon4);
    
    //icon for payment record button
    ImageIcon icon5 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\payment-method.png");
    Image img5 = icon5.getImage();
    Image imgscale5 = img5.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon5 = new ImageIcon(imgscale5);
    jlabelPaymentRecord1.setIcon(scaledIcon5);
    
    
    //icon for reset Password button
    ImageIcon icon6 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\password.png");
    Image img6 = icon6.getImage();
    Image imgscale6 = img6.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon6 = new ImageIcon(imgscale6);
    jlabelPaymentRecord.setIcon(scaledIcon6);
    
      //icon for register staff button
    ImageIcon icon7 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\team.png");
    Image img7 = icon7.getImage();
    Image imgscale7 = img7.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon7 = new ImageIcon(imgscale7);
    registerstaff.setIcon(scaledIcon7);
    
    //icon for register staff button
    ImageIcon icon8 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\staff.png");
    Image img8 = icon8.getImage();
    Image imgscale8 = img8.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon8 = new ImageIcon(imgscale8);
    managestaff.setIcon(scaledIcon8);
    
    
    
    
    
     }
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnPaymentRecord = new javax.swing.JPanel();
        jlabelPaymentRecord = new javax.swing.JLabel();
        lblpaymentrecord = new javax.swing.JLabel();
        panelManageRoom = new javax.swing.JPanel();
        lblManageRoomPic = new javax.swing.JLabel();
        lblManageRoom = new javax.swing.JLabel();
        panelManageBooking = new javax.swing.JPanel();
        lblAddRoompic = new javax.swing.JLabel();
        lblManageBooking = new javax.swing.JLabel();
        panelMakeBooking2 = new javax.swing.JPanel();
        lblMakeBookingPic = new javax.swing.JLabel();
        lblMakeBooking = new javax.swing.JLabel();
        paymentrecordpic = new javax.swing.JPanel();
        jlabelPaymentRecord1 = new javax.swing.JLabel();
        lblpaymentrecordpic = new javax.swing.JLabel();
        managebookingpic = new javax.swing.JPanel();
        lblManageBookingPic = new javax.swing.JLabel();
        lblmanagebooking = new javax.swing.JLabel();
        btnregisterstaffpic = new javax.swing.JPanel();
        registerstaff = new javax.swing.JLabel();
        lblregisterstaff = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnmaangestaff = new javax.swing.JPanel();
        managestaff = new javax.swing.JLabel();
        lblmaangestaff = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnPaymentRecord.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnPaymentRecord.setPreferredSize(new java.awt.Dimension(221, 282));
        btnPaymentRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaymentRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaymentRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPaymentRecordMouseExited(evt);
            }
        });

        jlabelPaymentRecord.setText("jLabel1");

        lblpaymentrecord.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblpaymentrecord.setText("Reset Password");

        javax.swing.GroupLayout btnPaymentRecordLayout = new javax.swing.GroupLayout(btnPaymentRecord);
        btnPaymentRecord.setLayout(btnPaymentRecordLayout);
        btnPaymentRecordLayout.setHorizontalGroup(
            btnPaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPaymentRecordLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jlabelPaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPaymentRecordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblpaymentrecord)
                .addGap(41, 41, 41))
        );
        btnPaymentRecordLayout.setVerticalGroup(
            btnPaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPaymentRecordLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jlabelPaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblpaymentrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        panelManageRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        panelManageRoom.setPreferredSize(new java.awt.Dimension(221, 282));
        panelManageRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageRoomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelManageRoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelManageRoomMouseExited(evt);
            }
        });

        lblManageRoomPic.setText("jLabel1");

        lblManageRoom.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblManageRoom.setText("Manage Room");

        javax.swing.GroupLayout panelManageRoomLayout = new javax.swing.GroupLayout(panelManageRoom);
        panelManageRoom.setLayout(panelManageRoomLayout);
        panelManageRoomLayout.setHorizontalGroup(
            panelManageRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageRoomLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblManageRoomPic, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelManageRoomLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(lblManageRoom)
                .addGap(46, 46, 46))
        );
        panelManageRoomLayout.setVerticalGroup(
            panelManageRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageRoomLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblManageRoomPic, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblManageRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        panelManageBooking.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        panelManageBooking.setPreferredSize(new java.awt.Dimension(221, 282));
        panelManageBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageBookingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelManageBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelManageBookingMouseExited(evt);
            }
        });

        lblAddRoompic.setText("jLabel1");

        lblManageBooking.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblManageBooking.setText("Add Room");

        javax.swing.GroupLayout panelManageBookingLayout = new javax.swing.GroupLayout(panelManageBooking);
        panelManageBooking.setLayout(panelManageBookingLayout);
        panelManageBookingLayout.setHorizontalGroup(
            panelManageBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageBookingLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(panelManageBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManageBooking)
                    .addComponent(lblAddRoompic, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        panelManageBookingLayout.setVerticalGroup(
            panelManageBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageBookingLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblAddRoompic, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lblManageBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        panelMakeBooking2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        panelMakeBooking2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMakeBooking2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMakeBooking2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMakeBooking2MouseExited(evt);
            }
        });

        lblMakeBookingPic.setText("jLabel1");

        lblMakeBooking.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblMakeBooking.setText("Make Booking");

        javax.swing.GroupLayout panelMakeBooking2Layout = new javax.swing.GroupLayout(panelMakeBooking2);
        panelMakeBooking2.setLayout(panelMakeBooking2Layout);
        panelMakeBooking2Layout.setHorizontalGroup(
            panelMakeBooking2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMakeBooking2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblMakeBookingPic, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMakeBooking2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMakeBooking)
                .addGap(46, 46, 46))
        );
        panelMakeBooking2Layout.setVerticalGroup(
            panelMakeBooking2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMakeBooking2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblMakeBookingPic, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMakeBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        paymentrecordpic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        paymentrecordpic.setPreferredSize(new java.awt.Dimension(221, 282));
        paymentrecordpic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentrecordpicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paymentrecordpicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paymentrecordpicMouseExited(evt);
            }
        });

        jlabelPaymentRecord1.setText("jLabel1");

        lblpaymentrecordpic.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblpaymentrecordpic.setText("Payment Record");

        javax.swing.GroupLayout paymentrecordpicLayout = new javax.swing.GroupLayout(paymentrecordpic);
        paymentrecordpic.setLayout(paymentrecordpicLayout);
        paymentrecordpicLayout.setHorizontalGroup(
            paymentrecordpicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentrecordpicLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jlabelPaymentRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentrecordpicLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblpaymentrecordpic)
                .addGap(37, 37, 37))
        );
        paymentrecordpicLayout.setVerticalGroup(
            paymentrecordpicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentrecordpicLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jlabelPaymentRecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lblpaymentrecordpic, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        managebookingpic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        managebookingpic.setPreferredSize(new java.awt.Dimension(221, 282));
        managebookingpic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managebookingpicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                managebookingpicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                managebookingpicMouseExited(evt);
            }
        });

        lblManageBookingPic.setText("jLabel1");

        lblmanagebooking.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblmanagebooking.setText("Manage Booking");

        javax.swing.GroupLayout managebookingpicLayout = new javax.swing.GroupLayout(managebookingpic);
        managebookingpic.setLayout(managebookingpicLayout);
        managebookingpicLayout.setHorizontalGroup(
            managebookingpicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managebookingpicLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblManageBookingPic, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managebookingpicLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblmanagebooking)
                .addGap(37, 37, 37))
        );
        managebookingpicLayout.setVerticalGroup(
            managebookingpicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managebookingpicLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblManageBookingPic, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblmanagebooking, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        btnregisterstaffpic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnregisterstaffpic.setPreferredSize(new java.awt.Dimension(221, 282));
        btnregisterstaffpic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregisterstaffpicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnregisterstaffpicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnregisterstaffpicMouseExited(evt);
            }
        });

        registerstaff.setText("jLabel1");

        lblregisterstaff.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblregisterstaff.setText("Register User");

        javax.swing.GroupLayout btnregisterstaffpicLayout = new javax.swing.GroupLayout(btnregisterstaffpic);
        btnregisterstaffpic.setLayout(btnregisterstaffpicLayout);
        btnregisterstaffpicLayout.setHorizontalGroup(
            btnregisterstaffpicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnregisterstaffpicLayout.createSequentialGroup()
                .addGroup(btnregisterstaffpicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnregisterstaffpicLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(registerstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnregisterstaffpicLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblregisterstaff)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        btnregisterstaffpicLayout.setVerticalGroup(
            btnregisterstaffpicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnregisterstaffpicLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(registerstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lblregisterstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 181, 204));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        btnmaangestaff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnmaangestaff.setPreferredSize(new java.awt.Dimension(221, 282));
        btnmaangestaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmaangestaffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmaangestaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmaangestaffMouseExited(evt);
            }
        });

        managestaff.setText("jLabel1");

        lblmaangestaff.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblmaangestaff.setText("Manage Staff");

        javax.swing.GroupLayout btnmaangestaffLayout = new javax.swing.GroupLayout(btnmaangestaff);
        btnmaangestaff.setLayout(btnmaangestaffLayout);
        btnmaangestaffLayout.setHorizontalGroup(
            btnmaangestaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnmaangestaffLayout.createSequentialGroup()
                .addGroup(btnmaangestaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnmaangestaffLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(managestaff, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnmaangestaffLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblmaangestaff)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        btnmaangestaffLayout.setVerticalGroup(
            btnmaangestaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnmaangestaffLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(managestaff, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lblmaangestaff, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnregisterstaffpic, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmaangestaff, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMakeBooking2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelManageRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentrecordpic, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(managebookingpic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelManageBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(managebookingpic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelMakeBooking2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelManageBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPaymentRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelManageRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paymentrecordpic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnmaangestaff, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnregisterstaffpic, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(379, 379, 379))))
                .addGap(82, 82, 82))
        );

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void paymentrecordpicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentrecordpicMouseExited
        paymentrecordpic.setBackground(new Color(214, 217, 223));
        lblpaymentrecordpic.setForeground(Color.black);
    }//GEN-LAST:event_paymentrecordpicMouseExited

    private void paymentrecordpicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentrecordpicMouseEntered
       paymentrecordpic.setBackground(Color.cyan);
       lblpaymentrecordpic.setForeground(Color.white);
    }//GEN-LAST:event_paymentrecordpicMouseEntered

    private void paymentrecordpicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentrecordpicMouseClicked
         managePaymentRecord frame = new managePaymentRecord();
        frame.setVisible(true);
    }//GEN-LAST:event_paymentrecordpicMouseClicked

    private void panelMakeBooking2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMakeBooking2MouseExited
        panelMakeBooking2.setBackground(new Color(214, 217, 223));
        lblMakeBooking.setForeground(Color.black);
    }//GEN-LAST:event_panelMakeBooking2MouseExited

    private void panelMakeBooking2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMakeBooking2MouseEntered
        panelMakeBooking2.setBackground(Color.cyan);
        lblMakeBooking.setForeground(Color.white);
    }//GEN-LAST:event_panelMakeBooking2MouseEntered

    private void panelMakeBooking2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMakeBooking2MouseClicked
          StaffSearchAvailableRoom frame = new StaffSearchAvailableRoom();
        frame.setVisible(true);
    }//GEN-LAST:event_panelMakeBooking2MouseClicked

    private void panelManageBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageBookingMouseExited
        panelManageBooking.setBackground(new Color(214, 217, 223));
        lblManageBooking.setForeground(Color.black);
    }//GEN-LAST:event_panelManageBookingMouseExited

    private void panelManageBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageBookingMouseEntered
        panelManageBooking.setBackground(Color.cyan);
        lblManageBooking.setForeground(Color.white);
    }//GEN-LAST:event_panelManageBookingMouseEntered

    private void panelManageBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageBookingMouseClicked
         StaffAddRoom frame = new StaffAddRoom();
        frame.setVisible(true);
    }//GEN-LAST:event_panelManageBookingMouseClicked

    private void panelManageRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageRoomMouseExited
        panelManageRoom.setBackground(new Color(214, 217, 223));
        lblManageRoom.setForeground(Color.black);
    }//GEN-LAST:event_panelManageRoomMouseExited

    private void panelManageRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageRoomMouseEntered
        panelManageRoom.setBackground(Color.cyan);
        lblManageRoom.setForeground(Color.white);
    }//GEN-LAST:event_panelManageRoomMouseEntered

    private void panelManageRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageRoomMouseClicked
        StaffManageRoom frame = new StaffManageRoom();
        frame.setVisible(true);
    }//GEN-LAST:event_panelManageRoomMouseClicked

    private void btnPaymentRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentRecordMouseExited
        btnPaymentRecord.setBackground(new Color(214, 217, 223));
        lblpaymentrecord.setForeground(Color.black);
    }//GEN-LAST:event_btnPaymentRecordMouseExited

    private void btnPaymentRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentRecordMouseEntered
        btnPaymentRecord.setBackground(Color.cyan);
        lblpaymentrecord.setForeground(Color.white);
    }//GEN-LAST:event_btnPaymentRecordMouseEntered

    private void btnPaymentRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentRecordMouseClicked
         resetpassword frame = new resetpassword();
        frame.setVisible(true);
    }//GEN-LAST:event_btnPaymentRecordMouseClicked

    private void managebookingpicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managebookingpicMouseClicked
       manageBooking frame = new manageBooking();
        frame.setVisible(true);
        
    }//GEN-LAST:event_managebookingpicMouseClicked

    private void managebookingpicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managebookingpicMouseEntered
      managebookingpic.setBackground(Color.cyan);
        lblmanagebooking.setForeground(Color.white);
        
        
        
    }//GEN-LAST:event_managebookingpicMouseEntered

    private void managebookingpicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managebookingpicMouseExited
       managebookingpic.setBackground(new Color(214, 217, 223));
        lblmanagebooking.setForeground(Color.black);
    }//GEN-LAST:event_managebookingpicMouseExited

    private void btnregisterstaffpicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregisterstaffpicMouseClicked
        AdminCreateUser frame = new AdminCreateUser();
        frame.setVisible(true);
    }//GEN-LAST:event_btnregisterstaffpicMouseClicked

    private void btnregisterstaffpicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregisterstaffpicMouseEntered
    btnregisterstaffpic.setBackground(Color.cyan);
        lblregisterstaff.setForeground(Color.white);
    }//GEN-LAST:event_btnregisterstaffpicMouseEntered

    private void btnregisterstaffpicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregisterstaffpicMouseExited
        btnregisterstaffpic.setBackground(new Color(214, 217, 223));
        lblregisterstaff.setForeground(Color.black);
    }//GEN-LAST:event_btnregisterstaffpicMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        LOGIN frame = new LOGIN();
        frame.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnmaangestaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaangestaffMouseClicked
       
        manageStaff frame = new manageStaff();
        frame.setVisible(true);
    }//GEN-LAST:event_btnmaangestaffMouseClicked

    private void btnmaangestaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaangestaffMouseEntered
        btnmaangestaff.setBackground(Color.cyan);
        lblmaangestaff.setForeground(Color.white);
    }//GEN-LAST:event_btnmaangestaffMouseEntered

    private void btnmaangestaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaangestaffMouseExited
         btnmaangestaff.setBackground(new Color(214, 217, 223));
        lblmaangestaff.setForeground(Color.black);
    }//GEN-LAST:event_btnmaangestaffMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newAdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPaymentRecord;
    private javax.swing.JPanel btnmaangestaff;
    private javax.swing.JPanel btnregisterstaffpic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabelPaymentRecord;
    private javax.swing.JLabel jlabelPaymentRecord1;
    private javax.swing.JLabel lblAddRoompic;
    private javax.swing.JLabel lblMakeBooking;
    private javax.swing.JLabel lblMakeBookingPic;
    private javax.swing.JLabel lblManageBooking;
    private javax.swing.JLabel lblManageBookingPic;
    private javax.swing.JLabel lblManageRoom;
    private javax.swing.JLabel lblManageRoomPic;
    private javax.swing.JLabel lblmaangestaff;
    private javax.swing.JLabel lblmanagebooking;
    private javax.swing.JLabel lblpaymentrecord;
    private javax.swing.JLabel lblpaymentrecordpic;
    private javax.swing.JLabel lblregisterstaff;
    private javax.swing.JPanel managebookingpic;
    private javax.swing.JLabel managestaff;
    private javax.swing.JPanel panelMakeBooking2;
    private javax.swing.JPanel panelManageBooking;
    private javax.swing.JPanel panelManageRoom;
    private javax.swing.JPanel paymentrecordpic;
    private javax.swing.JLabel registerstaff;
    // End of variables declaration//GEN-END:variables
}
