/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.booking.system;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Insets;

/**
 *
 * @author qi xian
 */
public class staffDashboard extends javax.swing.JFrame {

    /**
     * Creates new form staffDashboard
     */
    public staffDashboard() {
        initComponents();
        scaleImage();
    }

    
     public void scaleImage(){
    //icon for make booking button
    ImageIcon icon = new ImageIcon("C:\\Users\\qi xian\\Downloads\\calendar.png");
    Image img1 = icon.getImage();
    Image imgscale1 = img1.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(imgscale1);
    lblMakeBookingPic.setIcon(scaledIcon);
    
    //icon for manage booking button
    ImageIcon icon2 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\data.png");
    Image img2 = icon2.getImage();
    Image imgscale2 = img2.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon2 = new ImageIcon(imgscale2);
    lblManageBookingPic.setIcon(scaledIcon2);
    
    
    //icon for add room button
    ImageIcon icon3 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\room.png");
    Image img3 = icon3.getImage();
    Image imgscale3 = img3.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon3 = new ImageIcon(imgscale3);
    labelAddRoom.setIcon(scaledIcon3);
    
    //icon for manage room button
    ImageIcon icon4 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\medical-record.png");
    Image img4 = icon4.getImage();
    Image imgscale4 = img4.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon4 = new ImageIcon(imgscale4);
    lblManageRoomPic.setIcon(scaledIcon4);
    
    //icon for payment record button
    ImageIcon icon5 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\payment-method.png");
    Image img5 = icon5.getImage();
    Image imgscale5 = img5.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon5 = new ImageIcon(imgscale5);
    jlabelPaymentRecord.setIcon(scaledIcon5);
    
    
    //icon for reset Password button
    ImageIcon icon6 = new ImageIcon("C:\\Users\\qi xian\\Downloads\\password.png");
    Image img6 = icon6.getImage();
    Image imgscale6 = img6.getScaledInstance(108, 113, Image.SCALE_SMOOTH);
    ImageIcon scaledIcon6 = new ImageIcon(imgscale6);
    lblpasswordpic.setIcon(scaledIcon6);
   
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonIconDBeanInfo1 = new rojerusan.RSButtonIconDBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelManageBooking = new javax.swing.JPanel();
        lblManageBookingPic = new javax.swing.JLabel();
        lblManageBooking = new javax.swing.JLabel();
        panelAddRoom = new javax.swing.JPanel();
        labelAddRoom = new javax.swing.JLabel();
        lblAddRoom = new javax.swing.JLabel();
        panelMakeBooking2 = new javax.swing.JPanel();
        lblMakeBookingPic = new javax.swing.JLabel();
        lblMakeBooking = new javax.swing.JLabel();
        btnPaymentRecord = new javax.swing.JPanel();
        jlabelPaymentRecord = new javax.swing.JLabel();
        lblpaymentrecord = new javax.swing.JLabel();
        panelManageRoom = new javax.swing.JPanel();
        lblManageRoomPic = new javax.swing.JLabel();
        lblManageRoom = new javax.swing.JLabel();
        btnresetPassword = new javax.swing.JPanel();
        lblpasswordpic = new javax.swing.JLabel();
        lblresetpassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panelManageBooking.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        panelManageBooking.setPreferredSize(new java.awt.Dimension(221, 282));
        panelManageBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageBookingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelManageBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelManageBookingMouseExited(evt);
            }
        });

        lblManageBookingPic.setText("jLabel1");

        lblManageBooking.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblManageBooking.setText("Manage Booking");

        javax.swing.GroupLayout panelManageBookingLayout = new javax.swing.GroupLayout(panelManageBooking);
        panelManageBooking.setLayout(panelManageBookingLayout);
        panelManageBookingLayout.setHorizontalGroup(
            panelManageBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageBookingLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblManageBookingPic, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelManageBookingLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lblManageBooking)
                .addGap(32, 32, 32))
        );
        panelManageBookingLayout.setVerticalGroup(
            panelManageBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageBookingLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblManageBookingPic, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lblManageBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        panelAddRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        panelAddRoom.setPreferredSize(new java.awt.Dimension(221, 282));
        panelAddRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAddRoomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAddRoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAddRoomMouseExited(evt);
            }
        });

        labelAddRoom.setText("jLabel1");

        lblAddRoom.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblAddRoom.setText("Add Room");

        javax.swing.GroupLayout panelAddRoomLayout = new javax.swing.GroupLayout(panelAddRoom);
        panelAddRoom.setLayout(panelAddRoomLayout);
        panelAddRoomLayout.setHorizontalGroup(
            panelAddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddRoomLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(panelAddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddRoom)
                    .addComponent(labelAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelAddRoomLayout.setVerticalGroup(
            panelAddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddRoomLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(labelAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lblAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        panelMakeBooking2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        panelMakeBooking2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMakeBooking2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMakeBooking2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMakeBooking2MouseExited(evt);
            }
        });

        lblMakeBookingPic.setText("jLabel1");

        lblMakeBooking.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblMakeBooking.setText("Make Booking");

        javax.swing.GroupLayout panelMakeBooking2Layout = new javax.swing.GroupLayout(panelMakeBooking2);
        panelMakeBooking2.setLayout(panelMakeBooking2Layout);
        panelMakeBooking2Layout.setHorizontalGroup(
            panelMakeBooking2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMakeBooking2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblMakeBookingPic, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMakeBooking2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMakeBooking)
                .addGap(46, 46, 46))
        );
        panelMakeBooking2Layout.setVerticalGroup(
            panelMakeBooking2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMakeBooking2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblMakeBookingPic, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblMakeBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        btnPaymentRecord.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnPaymentRecord.setPreferredSize(new java.awt.Dimension(221, 282));
        btnPaymentRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaymentRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaymentRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPaymentRecordMouseExited(evt);
            }
        });

        jlabelPaymentRecord.setText("jLabel1");

        lblpaymentrecord.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblpaymentrecord.setText("Payment Record");

        javax.swing.GroupLayout btnPaymentRecordLayout = new javax.swing.GroupLayout(btnPaymentRecord);
        btnPaymentRecord.setLayout(btnPaymentRecordLayout);
        btnPaymentRecordLayout.setHorizontalGroup(
            btnPaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPaymentRecordLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jlabelPaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPaymentRecordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblpaymentrecord)
                .addGap(37, 37, 37))
        );
        btnPaymentRecordLayout.setVerticalGroup(
            btnPaymentRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPaymentRecordLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jlabelPaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblpaymentrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        panelManageRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        panelManageRoom.setPreferredSize(new java.awt.Dimension(221, 282));
        panelManageRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageRoomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelManageRoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelManageRoomMouseExited(evt);
            }
        });

        lblManageRoomPic.setText("jLabel1");

        lblManageRoom.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblManageRoom.setText("Manage Room");

        javax.swing.GroupLayout panelManageRoomLayout = new javax.swing.GroupLayout(panelManageRoom);
        panelManageRoom.setLayout(panelManageRoomLayout);
        panelManageRoomLayout.setHorizontalGroup(
            panelManageRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageRoomLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblManageRoomPic, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelManageRoomLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lblManageRoom)
                .addGap(46, 46, 46))
        );
        panelManageRoomLayout.setVerticalGroup(
            panelManageRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageRoomLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblManageRoomPic, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblManageRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        btnresetPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnresetPassword.setPreferredSize(new java.awt.Dimension(221, 282));
        btnresetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnresetPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnresetPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnresetPasswordMouseExited(evt);
            }
        });

        lblpasswordpic.setText("jLabel1");

        lblresetpassword.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblresetpassword.setText("Reset Password");

        javax.swing.GroupLayout btnresetPasswordLayout = new javax.swing.GroupLayout(btnresetPassword);
        btnresetPassword.setLayout(btnresetPasswordLayout);
        btnresetPasswordLayout.setHorizontalGroup(
            btnresetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnresetPasswordLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblpasswordpic, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnresetPasswordLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(lblresetpassword)
                .addGap(46, 46, 46))
        );
        btnresetPasswordLayout.setVerticalGroup(
            btnresetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnresetPasswordLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblpasswordpic, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblresetpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 181, 204));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMakeBooking2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelManageRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addGap(220, 220, 220)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panelManageBooking, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addGap(210, 210, 210))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAddRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnresetPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addGap(125, 125, 125))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelMakeBooking2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelManageBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPaymentRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelManageRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnresetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelManageBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageBookingMouseClicked
        manageBooking frame = new manageBooking();
        frame.setVisible(true);
        
        
    }//GEN-LAST:event_panelManageBookingMouseClicked

    private void panelManageBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageBookingMouseEntered
        panelManageBooking.setBackground(Color.cyan);
        lblManageBooking.setForeground(Color.white);
    }//GEN-LAST:event_panelManageBookingMouseEntered

    private void panelManageBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageBookingMouseExited
        panelManageBooking.setBackground(new Color(214, 217, 223));
        lblManageBooking.setForeground(Color.black);
    }//GEN-LAST:event_panelManageBookingMouseExited

    private void panelAddRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddRoomMouseClicked
        StaffAddRoom frame = new StaffAddRoom();
        frame.setVisible(true);
    }//GEN-LAST:event_panelAddRoomMouseClicked

    private void panelAddRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddRoomMouseEntered
    panelAddRoom.setBackground(Color.cyan);
        lblAddRoom.setForeground(Color.white);
    }//GEN-LAST:event_panelAddRoomMouseEntered

    private void panelAddRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddRoomMouseExited
        panelAddRoom.setBackground(new Color(214, 217, 223));
        lblAddRoom.setForeground(Color.black);
    }//GEN-LAST:event_panelAddRoomMouseExited

    private void panelMakeBooking2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMakeBooking2MouseClicked
        StaffSearchAvailableRoom frame = new StaffSearchAvailableRoom();
        frame.setVisible(true);
    }//GEN-LAST:event_panelMakeBooking2MouseClicked

    private void panelMakeBooking2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMakeBooking2MouseEntered
        panelMakeBooking2.setBackground(Color.cyan);
        lblMakeBooking.setForeground(Color.white);
    }//GEN-LAST:event_panelMakeBooking2MouseEntered

    private void panelMakeBooking2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMakeBooking2MouseExited
        panelMakeBooking2.setBackground(new Color(214, 217, 223));
        lblMakeBooking.setForeground(Color.black);
    }//GEN-LAST:event_panelMakeBooking2MouseExited

    private void btnPaymentRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentRecordMouseClicked
        managePaymentRecord frame = new managePaymentRecord();
        frame.setVisible(true);
    }//GEN-LAST:event_btnPaymentRecordMouseClicked

    private void btnPaymentRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentRecordMouseEntered
        btnPaymentRecord.setBackground(Color.cyan);
        lblpaymentrecord.setForeground(Color.white);
    }//GEN-LAST:event_btnPaymentRecordMouseEntered

    private void btnPaymentRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentRecordMouseExited
        btnPaymentRecord.setBackground(new Color(214, 217, 223));
        lblpaymentrecord.setForeground(Color.black);
    }//GEN-LAST:event_btnPaymentRecordMouseExited

    private void panelManageRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageRoomMouseClicked
        StaffManageRoom frame = new StaffManageRoom();
        frame.setVisible(true);
    }//GEN-LAST:event_panelManageRoomMouseClicked

    private void panelManageRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageRoomMouseEntered
        panelManageRoom.setBackground(Color.cyan);
        lblManageRoom.setForeground(Color.white);
    }//GEN-LAST:event_panelManageRoomMouseEntered

    private void panelManageRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageRoomMouseExited
        panelManageRoom.setBackground(new Color(214, 217, 223));
        lblManageRoom.setForeground(Color.black);
    }//GEN-LAST:event_panelManageRoomMouseExited

    private void btnresetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresetPasswordMouseClicked
        resetpassword frame = new resetpassword();
        frame.setVisible(true);
    }//GEN-LAST:event_btnresetPasswordMouseClicked

    private void btnresetPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresetPasswordMouseEntered
        btnresetPassword.setBackground(Color.cyan);
        lblresetpassword.setForeground(Color.white);
    }//GEN-LAST:event_btnresetPasswordMouseEntered

    private void btnresetPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresetPasswordMouseExited
       btnresetPassword.setBackground(new Color(214, 217, 223));
        lblresetpassword.setForeground(Color.black);
    }//GEN-LAST:event_btnresetPasswordMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        LOGIN frame = new LOGIN();
        frame.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPaymentRecord;
    private javax.swing.JPanel btnresetPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabelPaymentRecord;
    private javax.swing.JLabel labelAddRoom;
    private javax.swing.JLabel lblAddRoom;
    private javax.swing.JLabel lblMakeBooking;
    private javax.swing.JLabel lblMakeBookingPic;
    private javax.swing.JLabel lblManageBooking;
    private javax.swing.JLabel lblManageBookingPic;
    private javax.swing.JLabel lblManageRoom;
    private javax.swing.JLabel lblManageRoomPic;
    private javax.swing.JLabel lblpasswordpic;
    private javax.swing.JLabel lblpaymentrecord;
    private javax.swing.JLabel lblresetpassword;
    private javax.swing.JPanel panelAddRoom;
    private javax.swing.JPanel panelMakeBooking2;
    private javax.swing.JPanel panelManageBooking;
    private javax.swing.JPanel panelManageRoom;
    private rojerusan.RSButtonIconDBeanInfo rSButtonIconDBeanInfo1;
    // End of variables declaration//GEN-END:variables
}
