/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.booking.system;

import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;




import java.io.*;

import java.util.*;


/**
 *
 * @author qi xian
 */
public class StaffManageRoom extends javax.swing.JFrame {
      
    /**
     * Creates new form StaffManageRoom
     */
    public StaffManageRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAddRoom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManageRoom = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearchRoom = new javax.swing.JTextField();
        btnSearchRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblAddRoom.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblAddRoom.setForeground(new java.awt.Color(0, 182, 204));
        lblAddRoom.setText("Manage Room");
        lblAddRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 181, 204));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jTableManageRoom.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTableManageRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Floor Level", "Room Description", "Room Status", "Room Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableManageRoom);
        if (jTableManageRoom.getColumnModel().getColumnCount() > 0) {
            jTableManageRoom.getColumnModel().getColumn(0).setResizable(false);
            jTableManageRoom.getColumnModel().getColumn(1).setResizable(false);
            jTableManageRoom.getColumnModel().getColumn(2).setResizable(false);
            jTableManageRoom.getColumnModel().getColumn(3).setResizable(false);
            jTableManageRoom.getColumnModel().getColumn(4).setResizable(false);
            jTableManageRoom.getColumnModel().getColumn(5).setResizable(false);
        }

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 182, 204));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 182, 204));
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtSearchRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchRoomActionPerformed(evt);
            }
        });

        btnSearchRoom.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchRoom.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnSearchRoom.setForeground(new java.awt.Color(0, 182, 204));
        btnSearchRoom.setText("Search");
        btnSearchRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnSearchRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSearchRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchRoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchRoomMouseExited(evt);
            }
        });
        btnSearchRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAddRoom)
                        .addGap(175, 175, 175)
                        .addComponent(txtSearchRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(371, 371, 371)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(485, 485, 485))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchRoom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAddRoom)
                        .addComponent(jLabel1)
                        .addComponent(txtSearchRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 140, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String filePath = "C:\\Users\\qi xian\\Documents\\NetBeansProjects\\HOTEL BOOKING SYSTEM\\room.txt";
        File file = new File(filePath);
        jTableManageRoom.setRowHeight(30);
         jTableManageRoom.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 16));
        
        
        try{
            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel model = (DefaultTableModel)jTableManageRoom.getModel();
            Object[] tableLines = br.lines().toArray();
            
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                int index1 = line.indexOf(',');
                String[] dataRow = line.split(",");
                String roomNumber = dataRow[0];
                String rooomNumberComplete = roomNumber.substring(14,index1);
                dataRow[0] = rooomNumberComplete;
                
               
                model.addRow(dataRow);
            }
            
            
            
        } catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        DefaultTableModel model = (DefaultTableModel)jTableManageRoom.getModel();
        int selectedRowIndex = jTableManageRoom.getSelectedRow();
        
       
        if (selectedRowIndex >=0) {
            
        
        //passing value form staffManageroom.java to all textbox and combob
        StaffUpdateRoom transfer = new StaffUpdateRoom();
        StaffUpdateRoom.txtRoomNumber.setText(model.getValueAt(selectedRowIndex, 0).toString());
        StaffUpdateRoom.txtRoomDescription.setText(model.getValueAt(selectedRowIndex, 3).toString());
        StaffUpdateRoom.txtRoomId.setText(model.getValueAt(selectedRowIndex, 5).toString());
        
        
        String comboboxRoomType = model.getValueAt(selectedRowIndex, 1).toString();
        for (int i = 0; i < StaffUpdateRoom.cmbRoomType.getItemCount(); i++) {
            if (StaffUpdateRoom.cmbRoomType.getItemAt(i).toString().equalsIgnoreCase(comboboxRoomType)) {
                StaffUpdateRoom.cmbRoomType.setSelectedIndex(i);
            }
        }
        
          String comboboxFloorLevel = model.getValueAt(selectedRowIndex, 2).toString();
        for (int i = 0; i < StaffUpdateRoom.cmbFloorLevel.getItemCount(); i++) {
            if (StaffUpdateRoom.cmbFloorLevel.getItemAt(i).toString().equalsIgnoreCase(comboboxFloorLevel)) {
                StaffUpdateRoom.cmbFloorLevel.setSelectedIndex(i);
            }
        }
        
        String comboboxRoomStatus = model.getValueAt(selectedRowIndex, 4).toString();
        for (int i = 0; i < StaffUpdateRoom.cmbRoomStatus.getItemCount(); i++) {
            if (StaffUpdateRoom.cmbRoomStatus.getItemAt(i).toString().equalsIgnoreCase(comboboxRoomStatus)) {
                StaffUpdateRoom.cmbRoomStatus.setSelectedIndex(i);
            }
        }
        
        
        transfer.setVisible(true);}else{
            JOptionPane.showMessageDialog(null, "Please select a row!");
        
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        DefaultTableModel model = (DefaultTableModel)jTableManageRoom.getModel();
        int selectedRowIndex = jTableManageRoom.getSelectedRow();
        
        if (selectedRowIndex >= 0) {
            
        
        String roomIDToDeleteFrom = (model.getValueAt(selectedRowIndex, 5).toString());
        int roomIDToDeleteFromint = Integer.parseInt(roomIDToDeleteFrom);
        
        room obj = new room();
        
        obj.DeleteRoom(roomIDToDeleteFromint);
        
        
          //refresh jtable
        
          String filePath = "C:\\Users\\qi xian\\Documents\\NetBeansProjects\\HOTEL BOOKING SYSTEM\\room.txt";
        File file = new File(filePath);
        jTableManageRoom.setRowHeight(30);
         jTableManageRoom.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 16));
        
        
        try{
             model.setRowCount(0);
            BufferedReader br = new BufferedReader(new FileReader(file));
           
            Object[] tableLines = br.lines().toArray();
            
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                int index1 = line.indexOf(',');
                String[] dataRow = line.split(",");
                String roomNumber = dataRow[0];
                String rooomNumberComplete = roomNumber.substring(14,index1);
                dataRow[0] = rooomNumberComplete;
                
               
                model.addRow(dataRow);
            }
            
            
            
        } catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row!");
        
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRoomActionPerformed
       room obj = new room();
       obj.SerchRoom();
    }//GEN-LAST:event_btnSearchRoomActionPerformed

    private void txtSearchRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchRoomActionPerformed

    private void btnSearchRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRoomMouseEntered
       btnSearchRoom.setBackground(Color.cyan);
        btnSearchRoom.setForeground(Color.white);
    }//GEN-LAST:event_btnSearchRoomMouseEntered

    private void btnSearchRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchRoomMouseExited
        btnSearchRoom.setBackground(new Color(255,255,255));
        btnSearchRoom.setForeground(new Color(0,182,204));
    }//GEN-LAST:event_btnSearchRoomMouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        btnUpdate.setBackground(Color.cyan);
        btnUpdate.setForeground(Color.white);
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        btnUpdate.setBackground(new Color(255,255,255));
        btnUpdate.setForeground(new Color(0,182,204));
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setBackground(Color.cyan);
        btnDelete.setForeground(Color.white);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setBackground(new Color(255,255,255));
        btnDelete.setForeground(new Color(0,182,204));
    }//GEN-LAST:event_btnDeleteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearchRoom;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableManageRoom;
    private javax.swing.JLabel lblAddRoom;
    public static javax.swing.JTextField txtSearchRoom;
    // End of variables declaration//GEN-END:variables
}
