/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.booking.system;

import javax.swing.*;
import java.awt.*;




import java.io.*;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


/**
 *
 * @author qi xian
 */
public class StaffAddRoom extends javax.swing.JFrame {
   

    /**
     * Creates new form StaffAddRoom
     */
    public StaffAddRoom() {
        initComponents();
    }

    
    
   
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAddRoom = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblRoomNumber = new javax.swing.JLabel();
        lblRoomType = new javax.swing.JLabel();
        lblFloorLevel = new javax.swing.JLabel();
        lblRoomDescription = new javax.swing.JLabel();
        lblRoomStatus = new javax.swing.JLabel();
        txtRoomDescription = new javax.swing.JTextField();
        txtRoomNumber = new javax.swing.JTextField();
        cmbFloorLevel = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        cmbRoomType = new javax.swing.JComboBox<>();
        cmbRoomStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblAddRoom.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblAddRoom.setForeground(new java.awt.Color(0, 182, 204));
        lblAddRoom.setText("Add Room");
        lblAddRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRoomNumber.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblRoomNumber.setText("Room Number:");

        lblRoomType.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblRoomType.setText("Room Type:");

        lblFloorLevel.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblFloorLevel.setText("Floor Level:");

        lblRoomDescription.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblRoomDescription.setText("Room Description:");

        lblRoomStatus.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblRoomStatus.setText("Room Status:");

        txtRoomDescription.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        txtRoomDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        txtRoomDescription.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRoomDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRoomDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRoomDescriptionFocusLost(evt);
            }
        });
        txtRoomDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomDescriptionActionPerformed(evt);
            }
        });

        txtRoomNumber.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        txtRoomNumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        txtRoomNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRoomNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRoomNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRoomNumberFocusLost(evt);
            }
        });
        txtRoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomNumberActionPerformed(evt);
            }
        });

        cmbFloorLevel.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        cmbFloorLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        cmbFloorLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFloorLevelActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 182, 204));
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 182, 204), 4, true));
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cmbRoomType.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        cmbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabana", "Villa", "Suite", " " }));
        cmbRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoomTypeActionPerformed(evt);
            }
        });

        cmbRoomStatus.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        cmbRoomStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", " " }));
        cmbRoomStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoomStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRoomType)
                    .addComponent(lblFloorLevel)
                    .addComponent(lblRoomDescription)
                    .addComponent(lblRoomStatus)
                    .addComponent(lblRoomNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRoomDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFloorLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbRoomStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomNumber)
                    .addComponent(txtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomType)
                    .addComponent(cmbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFloorLevel)
                    .addComponent(cmbFloorLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomDescription)
                    .addComponent(txtRoomDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomStatus)
                    .addComponent(cmbRoomStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 181, 204));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAddRoom)
                        .addGap(444, 444, 444)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddRoom)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 140, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRoomDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRoomDescriptionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomDescriptionFocusGained

    private void txtRoomDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRoomDescriptionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomDescriptionFocusLost

    private void txtRoomDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomDescriptionActionPerformed

    private void txtRoomNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRoomNumberFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomNumberFocusGained

    private void txtRoomNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRoomNumberFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomNumberFocusLost

    private void txtRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomNumberActionPerformed

    private void cmbFloorLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFloorLevelActionPerformed

    }//GEN-LAST:event_cmbFloorLevelActionPerformed

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered

        btnSave.setBackground(Color.cyan);
        btnSave.setForeground(Color.white);

    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited

        btnSave.setBackground(new Color(255,255,255));
        btnSave.setForeground(new Color(0,182,204));

    }//GEN-LAST:event_btnSaveMouseExited

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         
        if ((txtRoomNumber.getText().equals("") || txtRoomDescription.getText().equals("") || cmbFloorLevel.getSelectedItem().toString().equals("") || cmbRoomType.getSelectedItem().toString().equals("") 
                || cmbRoomStatus.getSelectedItem().toString().equals("")) ) {
            JOptionPane.showMessageDialog(null, "Please Fill Up All Field!");}  else{
            String roomNumber = txtRoomNumber.getText();
            int roomNumberlength = roomNumber.length();
            
         
           
            
            
            
            
            
           
            
            String regex1 = "[0-9]+";  //must be all digits
            Pattern pattern1 = Pattern.compile(regex1);
            Matcher matcher1 = pattern1.matcher(roomNumber);
         
             
             
             if (matcher1.matches()== false  ) {
                JOptionPane.showMessageDialog(null, "Room number must be only digits.");
            }else if(roomNumberlength >4){
                JOptionPane.showMessageDialog(null, "NRoom Number Length Should Not Be Longer Tahn 4 digits");
            }
            else{
            
            String roomNumberS = txtRoomNumber.getText();
                 int  roomNumerInt = Integer.parseInt(roomNumberS);
            String floorLevell = cmbFloorLevel.getSelectedItem().toString();
                 int floorlevelint = Integer.parseInt(floorLevell);
                 
                 
                 
                 room obj = new room();
                 obj.CreateRoom(roomNumerInt, cmbRoomStatus.getSelectedItem().toString(), cmbRoomType.getSelectedItem().toString(), floorlevelint, txtRoomDescription.getText());
                 
                 
        }
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cmbRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoomTypeActionPerformed

    private void cmbRoomStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoomStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoomStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffAddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffAddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffAddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffAddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffAddRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbFloorLevel;
    private javax.swing.JComboBox<String> cmbRoomStatus;
    private javax.swing.JComboBox<String> cmbRoomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAddRoom;
    private javax.swing.JLabel lblFloorLevel;
    private javax.swing.JLabel lblRoomDescription;
    private javax.swing.JLabel lblRoomNumber;
    private javax.swing.JLabel lblRoomStatus;
    private javax.swing.JLabel lblRoomType;
    public static javax.swing.JTextField txtRoomDescription;
    public static javax.swing.JTextField txtRoomNumber;
    // End of variables declaration//GEN-END:variables
}
