/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.booking.system;
import static hotel.booking.system.StaffManageRoom.jTableManageRoom;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.*;





import java.io.*;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author qi xian
 */
public class StaffUpdateRoom extends javax.swing.JFrame {
    
    /**
     * Creates new form StaffUpdateRoom
     */
    public StaffUpdateRoom() {
        initComponents();
    }
    
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblSelectDay30 = new javax.swing.JLabel();
        btnUpdateRoom = new javax.swing.JButton();
        txtRoomNumber = new javax.swing.JTextField();
        lblSelectDay31 = new javax.swing.JLabel();
        lblSelectDay32 = new javax.swing.JLabel();
        lblSelectDay33 = new javax.swing.JLabel();
        lblSelectDay34 = new javax.swing.JLabel();
        txtRoomDescription = new javax.swing.JTextField();
        cmbRoomStatus = new javax.swing.JComboBox<>();
        cmbRoomType = new javax.swing.JComboBox<>();
        cmbFloorLevel = new javax.swing.JComboBox<>();
        lblSelectDay50 = new javax.swing.JLabel();
        txtRoomId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lblSelectDay30.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay30.setText("Room Number:");

        btnUpdateRoom.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        btnUpdateRoom.setText("Update");
        btnUpdateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRoomActionPerformed(evt);
            }
        });

        txtRoomNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRoomNumber.setEnabled(false);
        txtRoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomNumberActionPerformed(evt);
            }
        });

        lblSelectDay31.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay31.setText("Room Type:");

        lblSelectDay32.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay32.setText("Floor Level:");

        lblSelectDay33.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay33.setText("Room Status:");

        lblSelectDay34.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay34.setText("Room Description:");

        txtRoomDescription.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        cmbRoomStatus.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        cmbRoomStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive", " " }));

        cmbRoomType.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        cmbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabana", "Villa", "Suite", " " }));

        cmbFloorLevel.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        cmbFloorLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        lblSelectDay50.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay50.setText("Room ID:");

        txtRoomId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRoomId.setEnabled(false);
        txtRoomId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnUpdateRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelectDay30)
                            .addComponent(lblSelectDay31)
                            .addComponent(lblSelectDay32)
                            .addComponent(lblSelectDay33)
                            .addComponent(lblSelectDay34)
                            .addComponent(lblSelectDay50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbRoomStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRoomNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbRoomType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbFloorLevel, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRoomId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRoomDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectDay50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectDay30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectDay31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectDay32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFloorLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectDay33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRoomStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRoomDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectDay34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btnUpdateRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRoomActionPerformed

        room obj = new room();
        
      
        
        
           
        if ((txtRoomNumber.getText().equals("") || txtRoomDescription.getText().equals("") || cmbFloorLevel.getSelectedItem().toString().equals("") || cmbRoomType.getSelectedItem().toString().equals("") 
                || cmbRoomStatus.getSelectedItem().toString().equals("") || txtRoomId.getText().equals("")) ) {
            JOptionPane.showMessageDialog(null, "Please Fill Up All Field!");}  else{
            String roomNumberzzz = txtRoomNumber.getText();
            int roomNumberlength = roomNumberzzz.length();
            
         
           
            
            
            
            
            
           
            
            String regex1 = "[0-9]+";  //must be all digits
            Pattern pattern1 = Pattern.compile(regex1);
            Matcher matcher1 = pattern1.matcher(roomNumberzzz);
         
             
             
             if (matcher1.matches()== false  ) {
                JOptionPane.showMessageDialog(null, "Room number must be only digits.");
            }else if(roomNumberlength >4){
                JOptionPane.showMessageDialog(null, "NRoom Number Length Should Not Be Longer Tahn 4 digits");
            }
            else{
            
                  String RoomID = txtRoomId.getText();
        int RoomIDint = Integer.parseInt(RoomID);
        
        String RoomNumber = txtRoomNumber.getText();
        int RoomNumberint = Integer.parseInt(RoomNumber);
        
        String FloorLevel = cmbFloorLevel.getSelectedItem().toString();
        int FloorLevelint = Integer.parseInt(FloorLevel);
        
        obj.UpdateRoom(RoomIDint, RoomNumberint, cmbRoomStatus.getSelectedItem().toString(), cmbRoomType.getSelectedItem().toString(), FloorLevelint, txtRoomDescription.getText());
        this.dispose();
        
        //refresh jtable
        
          String filePath = "C:\\Users\\qi xian\\Documents\\NetBeansProjects\\HOTEL BOOKING SYSTEM\\room.txt";
        File file = new File(filePath);
        jTableManageRoom.setRowHeight(30);
         jTableManageRoom.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 16));
        
        
        try{
            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel model = (DefaultTableModel)jTableManageRoom.getModel();
             model.setRowCount(0);
            Object[] tableLines = br.lines().toArray();
            
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                int index1 = line.indexOf(',');
                String[] dataRow = line.split(",");
                String roomNumber = dataRow[0];
                String rooomNumberComplete = roomNumber.substring(14,index1);
                dataRow[0] = rooomNumberComplete;
                
               
                model.addRow(dataRow);
            }
            
            
            
        } catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
            }
        }
        
        
        
    }//GEN-LAST:event_btnUpdateRoomActionPerformed

    private void txtRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomNumberActionPerformed

    private void txtRoomIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffUpdateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffUpdateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffUpdateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffUpdateRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffUpdateRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateRoom;
    public static javax.swing.JComboBox<String> cmbFloorLevel;
    public static javax.swing.JComboBox<String> cmbRoomStatus;
    public static javax.swing.JComboBox<String> cmbRoomType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblSelectDay30;
    private javax.swing.JLabel lblSelectDay31;
    private javax.swing.JLabel lblSelectDay32;
    private javax.swing.JLabel lblSelectDay33;
    private javax.swing.JLabel lblSelectDay34;
    private javax.swing.JLabel lblSelectDay50;
    public static javax.swing.JTextField txtRoomDescription;
    public static javax.swing.JTextField txtRoomId;
    public static javax.swing.JTextField txtRoomNumber;
    // End of variables declaration//GEN-END:variables
}
