/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.booking.system;

import static hotel.booking.system.manageBooking.jTableManageBooking;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author qi xian
 */
public class staffUpdateBooking extends javax.swing.JFrame {

    /**
     * Creates new form staffUpdateBooking
     */
    public staffUpdateBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        lblSelectDay30 = new javax.swing.JLabel();
        btnUpdateBooking = new javax.swing.JButton();
        txtCustomerName = new javax.swing.JTextField();
        lblSelectDay31 = new javax.swing.JLabel();
        lblSelectDay32 = new javax.swing.JLabel();
        lblSelectDay33 = new javax.swing.JLabel();
        lblSelectDay50 = new javax.swing.JLabel();
        txtBookingId = new javax.swing.JTextField();
        txtIcPassport = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lblSelectDay30.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay30.setText("Customer Name:");

        btnUpdateBooking.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        btnUpdateBooking.setText("Update");
        btnUpdateBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBookingActionPerformed(evt);
            }
        });

        txtCustomerName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });

        lblSelectDay31.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay31.setText("IC / Passport:");

        lblSelectDay32.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay32.setText("Contact No:");

        lblSelectDay33.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay33.setText("Email:");

        lblSelectDay50.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay50.setText("Booking Id:");

        txtBookingId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBookingId.setEnabled(false);
        txtBookingId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookingIdActionPerformed(evt);
            }
        });

        txtIcPassport.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtIcPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIcPassportActionPerformed(evt);
            }
        });

        txtContactNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumberActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelectDay30)
                    .addComponent(lblSelectDay31)
                    .addComponent(lblSelectDay32)
                    .addComponent(lblSelectDay33)
                    .addComponent(lblSelectDay50))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBookingId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIcPassport, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(btnUpdateBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookingId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectDay50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectDay30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIcPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectDay31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectDay32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectDay33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnUpdateBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBookingActionPerformed
             if ((txtBookingId.getText().equals("") || txtCustomerName.getText().equals("") || txtIcPassport.getText().equals("")  || txtContactNumber.getText().equals("") || txtEmail.getText().equals("")) ) {
            JOptionPane.showMessageDialog(null, "Please Fill Up All Field!");} else{
                 
                 String customerName = txtCustomerName.getText();
            String contactNumber = txtContactNumber.getText();
            int contactNumberLength = contactNumber.length();
            char contactNumberFirstChar = contactNumber.charAt(0);//check if the first chracter of the phone number is 0
            char contactNumberSecondChar = contactNumber.charAt(1);//check if the first chracter of the phone number is 1
            
            
            String email = txtEmail.getText();
            String icnumber = txtIcPassport.getText();
            int icnumberLength = icnumber.length();
            
            String regex1 = "[0-9]+";  //must be all digits
            Pattern pattern1 = Pattern.compile(regex1);
            Matcher matcher1 = pattern1.matcher(icnumber);
            Matcher matcher2 = pattern1.matcher(contactNumber);
            
            String regex = "^(.+)@(.+)$";//email
            Pattern pattern = Pattern.compile(regex);
             Matcher matcher = pattern.matcher(email);
             
             String regex2 = "[A-Za-z ]*";//for only letter and spaces
             Pattern pattern3 = Pattern.compile(regex2);
             Matcher matcher3 = pattern3.matcher(customerName);
             
             
             
             if (matcher.matches()== false  ) {
                JOptionPane.showMessageDialog(null, "Invalid Email Format!");
            }else if(matcher1.matches() == false){
            JOptionPane.showMessageDialog(null, "Icnumber must be all digits!");
            }else if(icnumberLength != 12){
                JOptionPane.showMessageDialog(null, "Invalid Ic number Length! It must be 12 digits long!");
            }else if(matcher2.matches() == false){
                JOptionPane.showMessageDialog(null, "Contact Number must be all digits!");
            }else if(contactNumberLength != 10 && contactNumberLength != 11){
                JOptionPane.showMessageDialog(null, "Invalid Contact Number Lenth! It must be either 10 or 11 digits long!");}
            else if(contactNumberFirstChar != '0' || contactNumberSecondChar != '1'){
                JOptionPane.showMessageDialog(null, "Invalid Contact Number");
            }else if(matcher3.matches() == false){
                JOptionPane.showMessageDialog(null, "Name should only contain letter!");
            }
            else{
                 


        DefaultTableModel model = (DefaultTableModel)jTableManageBooking.getModel();
        int selectedRowIndex = jTableManageBooking.getSelectedRow();
        
        String duration = model.getValueAt(selectedRowIndex, 6).toString();
        int durationInt = Integer.parseInt(duration);
        booking obj = new booking(durationInt);

          
        String bookingID = txtBookingId.getText();
        

        
        
        String icpassport = txtIcPassport.getText();
        String contactno = txtContactNumber.getText();
        
        
        String checkinday = model.getValueAt(selectedRowIndex, 7).toString();
        String checkoutday= model.getValueAt(selectedRowIndex, 8).toString();
        String selecteddayyy= model.getValueAt(selectedRowIndex, 5).toString();
        
         obj.UpdateBookingRecord(bookingID , customerName, icpassport, contactno, email, checkinday, checkoutday,  selecteddayyy, false);
        this.dispose();
        
        //refresh jtable
        model.setRowCount(0);
        String filePath = "C:\\Users\\qi xian\\Documents\\NetBeansProjects\\HOTEL BOOKING SYSTEM\\booking.txt";
        File file = new File(filePath);
        jTableManageBooking.setRowHeight(30);
         jTableManageBooking.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 16));
        
        
        try{
            BufferedReader br = new BufferedReader(new FileReader(file));
            
            Object[] tableLines = br.lines().toArray();
            
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                int index1 = line.indexOf(',');
                String[] dataRow = line.split(",");
                
                String bookingId = dataRow[0];
                int bookingIdLength = bookingId.length();
                String bookingIdComplete = bookingId.substring(13,bookingIdLength);
                dataRow[0] = bookingIdComplete;
                
                
                
                
                String durationkk = dataRow[6];
                int durationkkLength = durationkk.length();
                String durationkkComplete = durationkk.substring(11,durationkkLength);
                dataRow[6] = durationkkComplete;
                
                String checkindaykk = dataRow[7];
                int checkindaykkLength = checkindaykk.length();
                String checkindaykkComplete = checkindaykk.substring(15,checkindaykkLength);
                dataRow[7] = checkindaykkComplete;
                
                String checkoutdaykk = dataRow[8];
                int checkoutdaykkLength = checkoutdaykk.length();
                String checkoutdaykkComplete = checkoutdaykk.substring(16,checkoutdaykkLength);
                dataRow[8] = checkoutdaykkComplete;
                
               
                model.addRow(dataRow);
            }
            
            
            
        } catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
             }
             }

    }//GEN-LAST:event_btnUpdateBookingActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtBookingIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookingIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookingIdActionPerformed

    private void txtIcPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIcPassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIcPassportActionPerformed

    private void txtContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumberActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffUpdateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffUpdateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffUpdateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffUpdateBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffUpdateBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateBooking;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblSelectDay30;
    private javax.swing.JLabel lblSelectDay31;
    private javax.swing.JLabel lblSelectDay32;
    private javax.swing.JLabel lblSelectDay33;
    private javax.swing.JLabel lblSelectDay50;
    public static javax.swing.JTextField txtBookingId;
    public static javax.swing.JTextField txtContactNumber;
    public static javax.swing.JTextField txtCustomerName;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtIcPassport;
    // End of variables declaration//GEN-END:variables
}
