/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.booking.system;

/**
 *
 * @author qi xian
 */
public class staffupdatebookingchangeroom extends javax.swing.JFrame {

    /**
     * Creates new form staffupdatebookingchangeroom
     */
    public staffupdatebookingchangeroom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbSelectAvailableRoom = new javax.swing.JComboBox<>();
        lblSelectAvailableRoom = new javax.swing.JLabel();
        btnSelectAvailableRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cmbSelectAvailableRoom.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        cmbSelectAvailableRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectAvailableRoomActionPerformed(evt);
            }
        });

        lblSelectAvailableRoom.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectAvailableRoom.setText("Available Room:");

        btnSelectAvailableRoom.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnSelectAvailableRoom.setText("Select");
        btnSelectAvailableRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAvailableRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblSelectAvailableRoom)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelectAvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSelectAvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectAvailableRoom)
                    .addComponent(cmbSelectAvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnSelectAvailableRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectAvailableRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAvailableRoomActionPerformed
        int day = 0;
        
        
        staffchangeroomupdatebookingday frame = new staffchangeroomupdatebookingday();
        

        String selectedRoom = cmbSelectAvailableRoom.getSelectedItem().toString();

        String selectedDay = staffupdatebookingChangeDayRoom.cmbSelectedDAy.getSelectedItem().toString();

        String duration = staffupdatebookingChangeDayRoom.cmbDuration.getSelectedItem().toString();
        
        staffchangeroomupdatebookingday.txtcheckinday.setText(selectedDay);
        staffchangeroomupdatebookingday.txtduration.setText(duration);
        staffchangeroomupdatebookingday.txtselectedroom.setText(selectedRoom);
        
        
                
                

        
        if (selectedDay =="Monday") {
            day = 1;

        }else if(selectedDay == "Tuesday"){
            day = 2;
        }else if(selectedDay == "Wednesday"){
            day = 3;
        }else if(selectedDay == "Thursday"){
            day = 4;
        }else if(selectedDay == "Friday"){
            day = 5;
        }else if(selectedDay == "Saturday"){
            day = 6;
        }else {
            day = 7;
        }

        int durationInt = Integer.parseInt(duration);

        int checkOutDay = day + durationInt;

        if (checkOutDay > 7) {
            checkOutDay = checkOutDay - 7;
        }

        if (checkOutDay == 1) {
             staffchangeroomupdatebookingday.txtCheckOutDay.setText("Monday");
        }else if(checkOutDay == 2){
             staffchangeroomupdatebookingday.txtCheckOutDay.setText("Tuesday");
        }else if(checkOutDay == 3){
             staffchangeroomupdatebookingday.txtCheckOutDay.setText("Wednesday");
        }else if(checkOutDay == 4){
             staffchangeroomupdatebookingday.txtCheckOutDay.setText("Thursday");
        }else if(checkOutDay == 5){
             staffchangeroomupdatebookingday.txtCheckOutDay.setText("Friday");
        }else if(checkOutDay == 6){
             staffchangeroomupdatebookingday.txtCheckOutDay.setText("Saturday");
        }else {
             staffchangeroomupdatebookingday.txtCheckOutDay.setText("Sunday");
        }

        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSelectAvailableRoomActionPerformed

    private void cmbSelectAvailableRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectAvailableRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelectAvailableRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffupdatebookingchangeroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffupdatebookingchangeroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffupdatebookingchangeroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffupdatebookingchangeroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffupdatebookingchangeroom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectAvailableRoom;
    public static javax.swing.JComboBox<String> cmbSelectAvailableRoom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSelectAvailableRoom;
    // End of variables declaration//GEN-END:variables
}
