/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.booking.system;

import static hotel.booking.system.manageBooking.jTableManageBooking;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static hotel.booking.system.manageStaff.jTableManageStaff;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author qi xian
 */
public class updateStaff extends javax.swing.JFrame {

    /**
     * Creates new form updateStaff
     */
    public updateStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        lblSelectDay30 = new javax.swing.JLabel();
        btnUpdateSTaff = new javax.swing.JButton();
        txtStaffPassword = new javax.swing.JTextField();
        lblSelectDay31 = new javax.swing.JLabel();
        lblSelectDay32 = new javax.swing.JLabel();
        lblSelectDay33 = new javax.swing.JLabel();
        lblSelectDay50 = new javax.swing.JLabel();
        txtStaffId = new javax.swing.JTextField();
        txtStaffEmail = new javax.swing.JTextField();
        txtStaffName = new javax.swing.JTextField();
        txtStaffUsername1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lblSelectDay30.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay30.setText("Staff Name:");

        btnUpdateSTaff.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        btnUpdateSTaff.setText("Update");
        btnUpdateSTaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSTaffActionPerformed(evt);
            }
        });

        txtStaffPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStaffPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffPasswordActionPerformed(evt);
            }
        });

        lblSelectDay31.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay31.setText("Staff Username:");

        lblSelectDay32.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay32.setText("Staff Password:");

        lblSelectDay33.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay33.setText("Staff Email:");

        lblSelectDay50.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        lblSelectDay50.setText("Staff ID:");

        txtStaffId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStaffId.setEnabled(false);
        txtStaffId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffIdActionPerformed(evt);
            }
        });

        txtStaffEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStaffEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffEmailActionPerformed(evt);
            }
        });

        txtStaffName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStaffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffNameActionPerformed(evt);
            }
        });

        txtStaffUsername1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStaffUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffUsername1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnUpdateSTaff, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(323, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelectDay30)
                            .addComponent(lblSelectDay31)
                            .addComponent(lblSelectDay32)
                            .addComponent(lblSelectDay33)
                            .addComponent(lblSelectDay50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtStaffPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(txtStaffId)
                            .addComponent(txtStaffEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStaffName)
                            .addComponent(txtStaffUsername1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                        .addGap(95, 95, 95))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectDay50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectDay30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectDay31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaffUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectDay32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectDay33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaffEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(btnUpdateSTaff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateSTaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSTaffActionPerformed
        staff obj = new staff();

        String staffID = txtStaffId.getText();
        int staffIDintint = Integer.parseInt(staffID);

        String staffName = txtStaffName.getText();
        
        String staffUsername = txtStaffUsername1.getText();
        
        String staffPassword = txtStaffPassword.getText();
        
        String staffEmail = txtStaffEmail.getText();
        

        
        if ((txtStaffName.getText().equals("") || txtStaffUsername1.getText().equals("") || txtStaffPassword.getText().equals("")  || txtStaffEmail.getText().equals("") || txtStaffId.getText().equals("") ) ) {
            JOptionPane.showMessageDialog(null, "Please Fill Up All Field!");} 
        
        else{
            String Name = txtStaffName.getText();
         
           
            
            
            String emailz = txtStaffEmail.getText();
            
            
           
            
            String regex = "^(.+)@(.+)$";//email
            Pattern pattern = Pattern.compile(regex);
             Matcher matcher = pattern.matcher(emailz);
             
             String regex2 = "[A-Za-z ]*";//for only letter and spaces
             Pattern pattern3 = Pattern.compile(regex2);
             Matcher matcher3 = pattern3.matcher(Name);
             
             
             
             if (matcher.matches()== false  ) {
                JOptionPane.showMessageDialog(null, "Invalid Email Format!");
            }else if(matcher3.matches() == false){
                JOptionPane.showMessageDialog(null, "Name should only contain letter!");
            }
            else{

       obj.UpdateStaff( staffIDintint,  staffName, staffUsername, staffPassword, staffEmail);
       this.dispose();
       
       
       //refresh jtable
      String filePath = "C:\\Users\\qi xian\\Documents\\NetBeansProjects\\HOTEL BOOKING SYSTEM\\staff.txt";
        File file = new File(filePath);
        jTableManageStaff.setRowHeight(30);
         jTableManageStaff.getTableHeader().setFont(new Font("SansSerif", Font.ITALIC, 16));
        
        
        try{
            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel model = (DefaultTableModel)jTableManageStaff.getModel();
             model.setRowCount(0);
            Object[] tableLines = br.lines().toArray();
            
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                int index1 = line.indexOf(',');
                
                
                
                
                String[] dataRow = line.split(",");
                
                    String[] tablerow ;
                    tablerow = new String[10];
                
                
                String email = dataRow[3];
                 tablerow[4] = email;
                
                
                String Password = dataRow[1];
                tablerow[3] = Password;
                
                
                 String Username = dataRow[0];
                  tablerow[2] = Username;
                
                
                 
                
                String staffId = dataRow[5];
                int staffIdLength = staffId.length();
                String staffIdComplete = staffId.substring(11,staffIdLength);
                tablerow[0] = staffIdComplete;
                
                
                String staffNamezz = dataRow[2];
                 tablerow[1] = staffNamezz;
                
               
                model.addRow(tablerow);
            }
            
            
            
        } catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
            }
        }
        

    }//GEN-LAST:event_btnUpdateSTaffActionPerformed

    private void txtStaffPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffPasswordActionPerformed

    private void txtStaffIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffIdActionPerformed

    private void txtStaffEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffEmailActionPerformed

    private void txtStaffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffNameActionPerformed

    private void txtStaffUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffUsername1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateSTaff;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblSelectDay30;
    private javax.swing.JLabel lblSelectDay31;
    private javax.swing.JLabel lblSelectDay32;
    private javax.swing.JLabel lblSelectDay33;
    private javax.swing.JLabel lblSelectDay50;
    public static javax.swing.JTextField txtStaffEmail;
    public static javax.swing.JTextField txtStaffId;
    public static javax.swing.JTextField txtStaffName;
    public static javax.swing.JTextField txtStaffPassword;
    public static javax.swing.JTextField txtStaffUsername1;
    // End of variables declaration//GEN-END:variables
}
